#include "OrderBook.h"

#include <iostream>

int main()
{
    OrderBook book;

    const auto firstAsk = book.addOrder(60, 10200, Side::Sell);
    if (!firstAsk) {
        std::cerr << "Failed to submit first ask\n";
        return 1;
    }

    const auto secondAsk = book.addOrder(50, 10300, Side::Sell);
    if (!secondAsk) {
        std::cerr << "Failed to submit second ask\n";
        return 1;
    }

    std::cout << "Book before matching:\n";
    book.printOrderBook();

    const auto aggressiveBuy = book.addOrder(100, 10300, Side::Buy);
    if (!aggressiveBuy) {
        std::cerr << "Failed to submit aggressive buy\n";
        return 1;
    }

    std::cout << "\nTrades generated by order " << aggressiveBuy->orderId << ":\n";
    for (const Trade& trade : aggressiveBuy->trades) {
        std::cout << "maker=" << trade.makerId
                  << " taker=" << trade.takerId
                  << " quantity=" << trade.executionQuantity
                  << " price=" << trade.executionPrice
                  << " takerSide=" << (trade.takerSide == Side::Buy ? "Buy" : "Sell")
                  << '\n';
    }

    std::cout << "\nBook after matching:\n";
    book.printOrderBook();

    if (!book.cancelOrder(secondAsk->orderId)) {
        std::cerr << "Failed to cancel remaining ask\n";
        return 1;
    }

    std::cout << "\nBook after cancellation:\n";
    book.printOrderBook();

    return 0;
}
